### ISSUE TITLE
Support amd64 releases of opa

### ISSUE THREAD

**Issue by pauly4it** [tochukwuvictor/asdf-opa#2]
**Is your feature request related to a problem? Please describe.**

Currently, the amd64 release of opa is hard-coded into the asdf-opa plugin. After installing on a mac with Apple silicon and trying to run opa, I received the following error:

```shell
/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash: line 28: /Users/myuser/.asdf/installs/opa/0.41.0/bin/opa: Bad CPU type in executable
/opt/homebrew/opt/asdf/libexec/lib/commands/command-exec.bash: line 28: /Users/myuser/.asdf/installs/opa/0.41.0/bin/opa: Undefined error: 0
```

**Describe the solution you'd like**

The asdf-opa plugin will need to read the machine architecture to fetch the appropriate opa release.

**Additional context**

PR is incoming for a proposed update to support amd64 opa releases.

**Comment by pauly4it** [comment]
@tochukwuvictor do you happen to have a linux arm64 machine you could test on by chance? My only concern is that the `uname -m` command doesn't return `arm64` on linux (though it should).

**Comment by tochukwuvictor** [comment]
Ah, good call. I don't but we should be able to verify on an ARM alpine image. Will take a look in a sec.

**Comment by tochukwuvictor** [comment]
Yeah, definitely good instincts. Returns `aarch64` on the latest alpine and ubuntu images.

**Comment by tochukwuvictor** [comment]
Agreed (on the case statement), and yeah if you wouldn't mind opening one more PR when you get a chance that would be great!

**Comment by pauly4it** [comment]
@tochukwuvictor appreciate the quick review of my PRs! Going to close this issue as resolved. 😀
